services:
  api:
    build: ./api
    depends_on:
      - db
      - web
    ports:
      - 5000:5000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./web:/app # Mount for hot reloading
    environment:
      - NODE_ENV=development  # Ensure development mode
    command: npm run dev # Start the dev server
  db:
    image: mariadb:10.11.5
    command: --secure-file-priv='/var/lib/mysql' --wait-timeout=3000 --interactive_timeout=1000 --innodb-buffer-pool-size=512M
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./dbconf:/usr/src/conf
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mariadbdata:
    driver: local
